name: C/C++ CI

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Configure git
      run: |
           git config user.name "enessmr"
           git config user.email "enessmr22@proton.me"

    - name: Commit 5 times
      run: |
            git pull origin master
            git add execs
            git commit -m "Update prebuilt binaries" || echo "No changes to commit"
            git pull --rebase origin master || echo "No remote changes to rebase"
          

    - name: Push all commits
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
    
